# Generated by Django 3.1.1 on 2020-09-03 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asistente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ApellidoPaterno', models.CharField(max_length=35)),
                ('ApellidoMaterno', models.CharField(max_length=35)),
                ('Nombres', models.CharField(max_length=35)),
                ('DNI', models.CharField(max_length=8)),
                ('Sexo', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino'), ('N', 'No especifica')], default='M', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
                ('Tipo', models.CharField(max_length=50)),
                ('Direccion', models.CharField(max_length=100)),
                ('Estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inscripcion', models.DateTimeField(auto_now_add=True)),
                ('asistente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionEvento.asistente')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionEvento.evento')),
            ],
        ),
    ]
